### ISSUE TITLE
[redwood] エラー内容

### ISSUE THREAD

**Issue by wafuwafu13** [wafuwafu13/redwoodblog#8]
```
GET /static/js/1.chunk.js 200 5.663 ms - -
GET /sockjs-node/info?t=1612751923476 200 3.016 ms - -
GET /sockjs-node/info?t=1612751923496 200 2.990 ms - -
api |
api | Error: Cannot query field "posts" on type "Query".
api |
api |
api | POST /graphql 400 2.179 ms - 1597
api |
api | GraphQLError: Cannot query field "posts" on type "Query".
api |
api |
api | 1 Object.Field
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48
api |
api | 2 Object.enter
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/graphql/language/visitor.js:323
api |
api | 3 Object.enter
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/graphql/utilities/TypeInfo.js:370
api |
api | 4 visit
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/graphql/language/visitor.js:243
api |
api | 5 Object.validate
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/graphql/validation/validate.js:69
api |
api | 6 validate
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/apollo-server-core/src/requestPipeline.ts:510
api |
api | 7 anonymous
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/apollo-server-core/src/requestPipeline.ts:296
api |
api | 8 fulfilled
api |   /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.6yeQqTNz/node_modules/apollo-server-core/dist/requestPipeline.js:5
api |
```

**Comment by wafuwafu13** [comment]
```
cy.exec('cd /var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.fjygi2nP; yarn rw prisma migrate dev') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stdout:
[2K[1G[2m$ /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.fjygi2nP/node_modules/.bin/rw prisma migrate dev[22m
[2K[1G[34minfo[39m Visit [1mhttps://yarnpkg.com/en/docs/cli...
Stderr:
rw prisma [...commands]

Run Prisma CLI with experimental features

位置:
  db push, push    Push the state from your Prisma schema to your database
                   without creating a migration
```

**Comment by wafuwafu13** [comment]
```
  at <unknown> (http://localhost:8910/__cypress/runner/cypress_runner.js:156511:27)
From previous event:
    at Context.exec (http://localhost:8910/__cypress/runner/cypress_runner.js:156484:106)
From Your Spec Code:
    at Context.eval (webpack:///cypress/integration/tutorial/tutorial.js:83:8)
```

**Comment by wafuwafu13** [comment]
<img width="748" alt="スクリーンショット 2021-02-08 12 17 49" src="https://user-images.githubusercontent.com/50798936/107172038-ade95f00-6a07-11eb-8689-82430e86a78f.png">

**Comment by wafuwafu13** [comment]
```
cy.exec(`cd ${BASE_DIR}; yarn rw db save`)
cy.exec(`cd ${BASE_DIR}; yarn rw db up`)
```


```
api |
api | TypeError: Cannot read property 'findMany' of undefined
api |
api | at /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.Vz8NJSsP/api/src/services/posts/posts.js(Object.posts):4
api | 1  import { db } from 'src/lib/db'
api | 2
api | 3  export const posts = () => {
api | 4    return db.post.findMany()
api | 5  }
api | 6
api | 7  export const post = ({ id }) => {
api | 8    return db.post.findUnique({
api | 9      where: { id },
api |



api | TypeError: Cannot read property 'create' of undefined
api |
api | at /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.Vz8NJSsP/api/src/services/posts/posts.js(Object.createPost):14
api | 9       where: { id },
api | 10    })
api | 11  }
api | 12
api | 13  export const createPost = ({ input }) => {
api | 14    return db.post.create({
api | 15      data: input,
api | 16    })
api | 17  }
api | 18
api | 19  export const updatePost = ({ id, input }) => {
api |
```

<img width="1418" alt="スクリーンショット 2021-02-08 12 51 39" src="https://user-images.githubusercontent.com/50798936/107174314-433b2200-6a0d-11eb-84bc-0fb1bb0f50be.png">

**Comment by wafuwafu13** [comment]
これでも通らない

```
cy.exec(
      `cd ${BASE_DIR}/api; yarn prisma migrate save --create-db --experimental --name ""`,
      {
        env: {
          DATABASE_URL: 'file:./dev.db',
          BINARY_TARGET: 'native',
        },
      }
    )

    cy.exec(`cd ${BASE_DIR}; yarn rw db up`)
    cy.exec(`cd ${BASE_DIR}; yarn rw g scaffold post`)
```

https://github.com/redwoodjs/redwood/commit/3086c3b98c728aa3dc0ca2cc64da32b7f7e0d2b7#diff-ef45626332de30c9e82d1da62a3ea4238292592195e94d9fad60acba247735f9R100
