### ISSUE TITLE
[redwood] issue出した後のエラー Cypress executable not found at: /Users/tagawahirotaka/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/MacOS/Cypress

### ISSUE THREAD

**Issue by wafuwafu13** [wafuwafu13/redwoodblog#9]
https://github.com/redwoodjs/redwood/issues/1754

```zsh
$ /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.FWYVCX3T/node_modules/.bin/rw dev --fwd=--open=false
$ /Users/tagawahirotaka/Desktop/redwood/tasks/e2e/node_modules/.bin/cypress open --env RW_PATH=/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.FWYVCX3T
No version of Cypress is installed in: /Users/tagawahirotaka/Library/Caches/Cypress/5.1.0/Cypress.app

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: /Users/tagawahirotaka/Library/Caches/Cypress/5.1.0/Cypress.app/Contents/MacOS/Cypress

----------

Platform: darwin (20.2.0)
Cypress Version: 5.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/desktop/redwood
  ✔ Generating the Prisma client...
$ /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.FWYVCX3T/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/config/webpack.development.js --open=false
$ /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.FWYVCX3T/node_modules/.bin/dev-server
api | Running at 'http://localhost:8911'
api | Watching files in '/private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.FWYVCX3T/api/src/functions'
web | ℹ ｢wds｣: Project is running at http://localhost:8910/
web | ℹ ｢wds｣: webpack output is served from /
web | ℹ ｢wds｣: Content not from webpack is served from /private/var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.FWYVCX3T/web
web | ℹ ｢wds｣: 404s will fallback to /index.html
api | Done. Took 3039ms.
```

**Comment by wafuwafu13** [comment]
http://localhost:8910/
は動く

**Comment by wafuwafu13** [comment]
```zsh
$ npm install -g cypress
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/tagawahirotaka/.npm-global/bin/cypress -> /Users/tagawahirotaka/.npm-global/lib/node_modules/cypress/bin/cypress

> cypress@6.4.0 postinstall /Users/tagawahirotaka/.npm-global/lib/node_modules/cypress
> node index.js --exec install

Installing Cypress (version: 6.4.0)

  ✔  Downloaded Cypress
  ✔  Unzipped Cypress
  ✔  Finished Installation /Users/tagawahirotaka/Library/Caches/Cypress/6.4.0

⚠ Warning: It looks like you've installed Cypress globally.

  This will work, but it's not recommended.

  The recommended way to install Cypress is as a devDependency per project.

  You should probably run these commands:

  - npm uninstall -g cypress
  - npm install --save-dev cypress
+ cypress@6.4.0
added 217 packages from 148 contributors in 67.574s
```

**Comment by wafuwafu13** [comment]
```
$ npm uninstall -g cypress
removed 217 packages in 2.742s
```

**Comment by wafuwafu13** [comment]
```
$ npm i
```

**Comment by wafuwafu13** [comment]
```zsh
$ ./tasks/test-tutorial
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.19s.
You have not supplied a path to a Redwood project.
We will create one for you.
We will copy './packages/create-redwood-app/template' and the packages/*
yarn run v1.21.1
$ /Users/tagawahirotaka/Desktop/redwood/node_modules/.bin/babel-node dist/create-redwood-app.js /var/folders/h0/n4dr2mwn6vqbtk9y1zrcykd80000gn/T/redwood.pB3mEamU --no-yarn-install
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'check-node-version'
Require stack:
- /Users/tagawahirotaka/Desktop/redwood/packages/create-redwood-app/dist/create-redwood-app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/tagawahirotaka/Desktop/redwood/packages/create-redwood-app/dist/create-redwood-app.js:21:48)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._compile (/Users/tagawahirotaka/Desktop/redwood/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.newLoader [as .js] (/Users/tagawahirotaka/Desktop/redwood/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1050:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tagawahirotaka/Desktop/redwood/packages/create-redwood-app/dist/create-redwood-app.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wafuwafu13** [comment]
```
$ yarn install
```

**Comment by wafuwafu13** [comment]
```
$ /Users/tagawahirotaka/Desktop/redwood/tasks/e2e/node_modules/.bin/cypress install
```

**Comment by wafuwafu13** [comment]
```zsh
~/desktop/redwood
$ /Users/tagawahirotaka/Desktop/redwood/tasks/e2e/node_modules/.bin/cypress install
Installing Cypress (version: 5.1.0)

  ✔  Downloaded Cypress
  ✔  Unzipped Cypress
  ✔  Finished Installation /Users/tagawahirotaka/Library/Caches/Cypress/5.1.0

You can now open Cypress by running: node_modules/.bin/cypress open

https://on.cypress.io/installing-cypress
```

**Comment by wafuwafu13** [comment]
```zsh
$ cd /Users/tagawahirotaka/Library/Caches/Cypress
~/Library/Caches/Cypress
$ ls
5.1.0   6.4.0
```
